name: Rust

on:
  workflow_dispatch:

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SERVER: ${{ secrets.SERVER }}
  SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
  USER: ${{ secrets.USER }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
    
jobs:
  deployment:

    runs-on: ubuntu-latest
    
    environment: deploy_loader

    steps:
    - uses: actions/checkout@v3

    - name: Cache Cargo registry
      uses: actions/cache@v2
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache target directory
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-target-release-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Check
      run: echo $USER $SERVER $SERVER_PASSWORD

    - name: Check2
      run: echo ${{ secrets.USER }} ${{ secrets.SERVER }} ${{ secrets.SERVER_PASSWORD }}

    - name: Check3
      run: echo $CHECK
    
    - name: Deploy script
      run: bash ./crate/receiver/script/semi-auto-deploy.sh
